### ISSUE TITLE
App is freezing on auth fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1920]
**Describe the bug**
The app is freezing on auth fragment in API 28
- Due to google smart authentication

**Comment by liveHarshit** [comment]
@anhanh11001 This issue is after PR #1901 . Please help me to figure out the problem.

**Comment by anhanh11001** [comment]
Yes, I'm working on it now

**Comment by anhanh11001** [comment]
@liveHarshit can you tell me how to reproduce it?

**Comment by liveHarshit** [comment]
> @liveHarshit can you tell me how to reproduce it?

Save credentials with Google smart lock and log out.
After opening auth fragment app is freezing, but while reverting changes in #1901, working fine.
Logs are not there because it is due to a memory leak.

**Comment by liveHarshit** [comment]
@anhanh11001 Are you able to reproduce it. This issue is with the play store build variant.

**Comment by anhanh11001** [comment]
Not really, I'm using my emulator. What should I do to test it with play store variant

**Comment by liveHarshit** [comment]
> Not really, I'm using my emulator. What should I do to test it with play store variant

First of all your google account should signed in the device.
Go to build -> Buid variant and select playstoredebug and run the app.

**Comment by liveHarshit** [comment]
Logs - 
```
E/Parcel: Reading a NULL string not supported here.
D/LeakCanary: Checking retained instances because found new instance retained
    Found 1 retained instances, which is less than the visible threshold of 5
I/Choreographer: Skipped 1 frames!  The application may be doing too much work on its main thread.
D/LeakCanary: Watching instance of android.widget.FrameLayout with key 1e8c7eb0-6102-4c8a-8a78-60ed219867e2
D/LeakCanary: Watching instance of android.widget.ScrollView with key 9ed3b1c2-a30e-413e-b5cc-1944558ad619
D/LeakCanary: Watching instance of android.widget.FrameLayout with key de7c38a2-fb5d-4950-bd98-c1665d333edb
D/LeakCanary: Watching instance of android.widget.ScrollView with key 7ebf60e1-f2c6-486f-bcfd-bdc8bed33cc6
D/LeakCanary: Watching instance of android.widget.FrameLayout with key 098ec26f-12f0-4f2f-a5d4-853563776719
D/LeakCanary: Watching instance of android.widget.ScrollView with key 42cc7f0f-1bd6-43f5-b771-e6f53a452e19
D/LeakCanary: Watching instance of android.widget.FrameLayout with key 208dcaea-4e31-496e-a706-23ea6ac08a11
D/LeakCanary: Watching instance of android.widget.ScrollView with key ee2d485f-4f6e-47da-94b3-833608aa703d
.
.
..
.
.
Infinite times.
```

**Comment by anhanh11001** [comment]
ok I get it

**Comment by liveHarshit** [comment]
I think I got the problem, let me explain

**Comment by anhanh11001** [comment]
ok please

**Comment by liveHarshit** [comment]
While redirecting to auth fragment, it is observing credentials from google smart lock, if credentials are there, it is redirected to login fragment. So, the text is going to change in the email text input layout. Due to text watcher, Again it pop up to auth fragment, now again credentials are observing from google smart lock and the whole process is repeating.

**Comment by anhanh11001** [comment]
oh then #1924 should fix it

**Comment by liveHarshit** [comment]
> oh then #1924 should fix it

But I have tested changes in the PR, this issue is still there. Let me check again.

**Comment by liveHarshit** [comment]
Tested not solved with #1924. Because smart lock credentials not passing through arguments.
