### ISSUE TITLE
Welcome Fragment loading again when back pressed.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#992]
**Describe the bug**

Welcome Fragment comes again when back pressed from events fragment.

**To Reproduce**

Go to the events page and press back

**Expected behavior**

App should quit on back pressed twice

**Logs**

**Screenshots**

![back_error](https://user-images.githubusercontent.com/34534870/52081666-d50f2980-25c0-11e9-8d0c-89a12060bc05.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|Android Pie 9.0.3 |

**Additional context**

@liveHarshit Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
Sorry, I'm not able to reproduce the issue. And there is no reason for this issue because start destination for navigation is Event fragment. Can you describe exactly why it is happening **especially in your device**?

**Comment by liveHarshit** [comment]
And also in GIF, it is not clear, as far as I can see there is sliding animation from Welcome fragment to Events fragment.

**Comment by kshitijsuri90** [comment]
It's showing on first-time installation. Install the app the app from beginning and select current location from the welcome fragment and when you navigate to events fragment press back and see @liveHarshit

**Comment by kshitijsuri90** [comment]
I think the error is happening because on back pressed the controller navigates to welcome fragment but since the start fragment is event fragment it tries to go back to it. So for a second welcome fragment is shown. @liveHarshit

**Comment by liveHarshit** [comment]
> It's showing on first-time installation. Install the app the app from beginning and select current location from the welcome fragment and when you navigate to events fragment press back and see @liveHarshit

Yes, now I'm able to reproduce it. Please go ahead.

**Comment by AnEnigmaticBug** [comment]
@kshitijsuri90, @liveHarshit  can I work on this issue?

**Comment by liveHarshit** [comment]
This issue is solved.

**Comment by AnEnigmaticBug** [comment]
@liveHarshit I'm still seeing this issue. I've the latest code in the development branch.

**Comment by AnEnigmaticBug** [comment]
Steps to reproduce:
1. In the welcome screen, use the "Use my current location" button.
2. Once the events screen loads up, press the back button.

**Comment by liveHarshit** [comment]
> Steps to reproduce:
> 
> 1. In the welcome screen, use the "Use my current location" button.
> 2. Once the events screen loads up, press the back button.

Okay, I will test it.

**Comment by liveHarshit** [comment]
Yes, it is not resolved. 

> I think the error is happening because on back pressed the controller navigates to welcome fragment but since the start fragment is event fragment it tries to go back to it. So for a second welcome fragment is shown. @liveHarshit

@kshitijsuri90 Please add nav options for clear back stack while navigating. 

@AnEnigmaticBug ask @kshitijsuri90 if you want to work on this issue.

**Comment by AnEnigmaticBug** [comment]
@kshitijsuri90 can I work on this issue?

**Comment by AnEnigmaticBug** [comment]
@liveHarshit since @kshitijsuri90 isn't replying, can I make a pull-request for this issue?

**Comment by liveHarshit** [comment]
/remind me to check the status in 2 days

**Comment by liveHarshit** [comment]
> Please add nav options for clear back stack while navigating.

@AnEnigmaticBug

**Comment by AnEnigmaticBug** [comment]
Ok

**Comment by AnEnigmaticBug** [comment]
I'll push my code soon
